---
schema:
  procedures: {}
  tables:
    data:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - data_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - file_id
            - sheet_id
            - row_indx
          match_type: ''
          name: file_id_sheet_id_row_indx_unique
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 0
          expression: ''
          fields:
            - file_id
          match_type: ''
          name: data_fk_file_id
          on_delete: NO ACTION
          on_update: NO ACTION
          options: []
          reference_fields:
            - file_id
          reference_table: dataset
          type: FOREIGN KEY
        - deferrable: 0
          expression: ''
          fields:
            - sheet_id
          match_type: ''
          name: data_fk_sheet_id
          on_delete: NO ACTION
          on_update: NO ACTION
          options: []
          reference_fields:
            - sheet_id
          reference_table: datasheet
          type: FOREIGN KEY
      fields:
        age:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: age
          order: 6
          size:
            - 0
        data_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: data_id
          order: 1
          size:
            - 0
        file_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: file_id
          order: 2
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 5
          size:
            - 0
        row_indx:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: row_indx
          order: 4
          size:
            - 0
        sheet_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: sheet_id
          order: 3
          size:
            - 0
        utf:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: utf
          order: 7
          size:
            - 0
      indices:
        - fields:
            - file_id
          name: data_idx_file_id
          options: []
          type: NORMAL
        - fields:
            - sheet_id
          name: data_idx_sheet_id
          options: []
          type: NORMAL
      name: data
      options: []
      order: 3
    dataset:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - file_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        file:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: file
          order: 2
          size:
            - 0
        file_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: file_id
          order: 1
          size:
            - 0
        transaction_date:
          data_type: timestamp
          default_value: !!perl/ref
            =: current_timestamp
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: transaction_date
          order: 3
          size:
            - 0
      indices: []
      name: dataset
      options: []
      order: 1
    datasheet:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - sheet_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - file_id
            - sheet_indx
          match_type: ''
          name: file_id_sheet_indx_unique
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 0
          expression: ''
          fields:
            - file_id
          match_type: ''
          name: datasheet_fk_file_id
          on_delete: NO ACTION
          on_update: NO ACTION
          options: []
          reference_fields:
            - file_id
          reference_table: dataset
          type: FOREIGN KEY
      fields:
        file_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: file_id
          order: 2
          size:
            - 0
        sheet_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: sheet_id
          order: 1
          size:
            - 0
        sheet_indx:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: sheet_indx
          order: 3
          size:
            - 0
        sheet_name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: sheet_name
          order: 4
          size:
            - 0
      indices:
        - fields:
            - file_id
          name: datasheet_idx_file_id
          options: []
          type: NORMAL
      name: datasheet
      options: []
      order: 2
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Data
      - Dataset
      - Datasheet
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11024
